services:
  clone:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: clone
    tty: true
    volumes:
      - /app/node_modules 
      - type: bind
        source: ../
        target: /app
